### ISSUE TITLE
puredata path missing forwardslash ...

### ISSUE THREAD

**Issue by stuaxo** [nodebox/nodebox-opengl#13]
On Ubuntu the sound examples don't work ..
```
$ python 01-fft.py 
Exception AttributeError: "'FreeTypeMemoryFace' object has no attribute 'ft_face'" in <bound method FreeTypeMemoryFace.__del__ of <pyglet.font.freetype.FreeTypeMemoryFace object at 0x7f6bd43fde10>> ignored
Exception AttributeError: "'FreeTypeMemoryFace' object has no attribute 'ft_face'" in <bound method FreeTypeMemoryFace.__del__ of <pyglet.font.freetype.FreeTypeMemoryFace object at 0x7f6bd43fde10>> ignored
Traceback (most recent call last):
  File "01-fft.py", line 23, in <module>
    pd = PD("01-fft.pd", buffer=16, start=True)
  File "../../nodebox/sound/process.py", line 214, in __init__
    self.start()
  File "../../nodebox/sound/process.py", line 232, in start
    raise PDError, "no PD application found"
nodebox.sound.process.PDError: no PD application found
```

But it's easily fixable by changing /nodebox/sound/process.py around line 199 and making sure all the paths have a / at the start.

**Comment by stuaxo** [comment]
^ fix in pull request.
