### ISSUE TITLE
OSX: ImportError: cannot import name pointer

### ISSUE THREAD

**Issue by graphific** [nodebox/nodebox-opengl#8]
"ImportError: cannot import name pointer" can be fixed with:
- edit nodebox/graphics/geometry.py:
  delete "pointer" import and change "pointer(data)" to "POINTER(data)"

error: "NameError: global name 'c_uint' is not defined" can be fixed with:
- edit nodebox/graphics/shaders.py:
  add "from ctypes import c_uint"

**Comment by techtonik** [comment]
The same problem on Windows.
```
nodebox-gl-1.7\examples\01-basics>python.exe 01-rect.py
Traceback (most recent call last):
  File "01-rect.py", line 5, in <module>
    from nodebox.graphics import *
  File "..\..\nodebox\graphics\__init__.py", line 1, in <module>
    import bezier
  File "..\..\nodebox\graphics\bezier.py", line 10, in <module>
    from context import BezierPath, PathElement, PathError, Point, MOVETO, LINETO, CURVETO, CLOSE
  File "..\..\nodebox\graphics\context.py", line 29, in <module>
    import geometry
  File "..\..\nodebox\graphics\geometry.py", line 454, in <module>
    from pyglet.gl import \
ImportError: cannot import name pointer
```

**Comment by techtonik** [comment]
https://stackoverflow.com/questions/23435690/installing-nodeboxopengl-on-windows

**Comment by techtonik** [comment]
https://stackoverflow.com/questions/35730631/cannot-import-nodebox-graphics-on-python

**Comment by karstenw** [comment]
Try my fork: https://github.com/karstenw/nodebox-opengl

It runs nice on OSX with current Python2, current pyglet and is installable. Haven't tested it on win/linux.

**Comment by vkopey** [comment]
Try [nodebox-opengl 1.6.1](https://pypi.org/project/nodebox-opengl/) + pyglet-1.3.3
